networks:
  monitoring:
    driver: bridge

volumes:
  my_db:
  my_media:
  prometheus_data: {}
  grafana-data: {}

services:
  air_service:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - my_media:/files/media
    depends_on:
      - db
      - redis
    networks:
      - monitoring

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA
    networks:
      - monitoring

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring

  celery:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "celery -A airport_api_service worker --loglevel=info"
    depends_on:
      - db
      - redis
    networks:
      - monitoring

  celery-beat:
    build:
      context: .
    user: my_user
    command: "celery -A airport_api_service beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    restart: on-failure
    networks:
      - monitoring

  flower:
    build:
      context: .
    ports:
      - "5555:5555"
    command: "celery -A airport_api_service flower --address=0.0.0.0"
    depends_on:
      - celery
      - celery-beat
    env_file:
      - .env
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring
