# Generated by Django 5.1.1 on 2024-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="airplanes", to="air_service.crew"
            ),
        ),
    ]
