# Generated by Django 5.1.1 on 2024-10-01 19:22

import air_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0003_airplane_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=air_service.models.airplane_image_path
            ),
        ),
    ]
