# Generated by Django 5.1.1 on 2024-10-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0005_ticket_notification_sent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "country")},
        ),
    ]
